services:
  app:
    build: .
    ports:
      - '4000:4000'
    restart: always
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      URL_BACKEND: ${URL_BACKEND}
      URL_IDEAL_LOCAL: ${URL_IDEAL_LOCAL}
      EMAIL: ${EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      PRODUTION: ${PRODUTION}
    command: node ./dist/index.js
